config/routes.rb
InPlaceEditableTableDemo::Application.routes.draw do

  resources :albums, only: [:index, :destroy, :update, :create]
  root 'albums#index'
  

  

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, presence: true
  validates :year, numericality: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:update, :destroy]
  before_filter :clear_flash

  def index
    @albums = Album.all
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = 'Album was successfully created.'
      @albums = Album.all
    else
      flash[:error] = @album.errors.full_messages.join(', ')
    end
  end

  def update
    @album.assign_attributes(album_params)
    if @album.save
      flash[:notice] = 'Album was successfully updated.'
    else
      flash[:error] = @album.errors.full_messages.join(', ')
    end
  end

  def destroy
    if @album.destroy
      flash[:notice] = 'Album deleted successfully'
    else
      flash[:error] = 'Album could not be deleted'
    end
    @albums = Album.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :artist, :year, :genre)
    end

    def clear_flash
      flash.clear
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album_table_row.html.haml
%td= album.name
%td= album.artist
%td= album.year
%td= album.genre
%td
  = link_to 'Edit', 'javascript:void(0)', class: 'btn edit_btn'
  %span
  = link_to 'Delete', album_path(album), method: 'delete', data: {confirm: 'Are you sure?'}, remote: true, class: 'btn'

app/views/albums/_albums.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Name
      %th Artist
      %th Year
      %th Genre
      %th Actions
  %tbody
    - if @albums.present?
      - @albums.each do |album|
        %tr{'data-id' => "#{album.id}"}
          = render 'album_table_row', album: album

    %tr.hide
      = form_for :album, url: albums_path, remote: true, html: {id: 'create_album_form'} do |f|
        %td= f.text_field :name, class: 'input-small'
        %td= f.text_field :artist, class: 'input-small'
        %td= f.text_field :year, class: 'input-small'
        %td= f.text_field :genre, class: 'input-small'
        %td
          = f.submit 'Save', class: 'btn'
          %span
          = link_to 'Cancel', 'javascript:void(0)', class: 'btn cancel_btn'
= link_to 'New Album', 'javascript:void(0)', class: 'btn', id: 'create_btn'

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/create.js.haml
- if @albums.present?
  $('#album_table').html("#{escape_javascript(render 'albums')}")
$('.flash_message').html('#{escape_javascript(render 'flash_message')}');
$('.alert').delay(5000).fadeOut("slow", function () { $(this).remove();})

app/views/albums/destroy.js.haml
- if @albums.present?
  $('#album_table').html("#{escape_javascript(render 'albums')}")
$('.flash_message').html('#{escape_javascript(render 'flash_message')}');
$('.alert').delay(5000).fadeOut("slow", function () { $(this).remove();})

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.haml
%h3 Listing albums
#album_table
  = render 'albums'

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @album.genre %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/albums/update.js.haml
- if @album.present? && flash[:error].blank?
  $('#album_table').find('tr[data-id="#{params[:id]}"]').html('#{escape_javascript(render 'album_table_row', album: @album)}')
$('.flash_message').html('#{escape_javascript(render 'flash_message')}');
$('.alert').delay(5000).fadeOut("slow", function () { $(this).remove();})

app/views/application/_flash_message.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, class: "alert flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title In Place Editable Table
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application" #, "data-turbolinks-track" => false
    = csrf_meta_tags
    %script
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),      
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-47731342-1', 'in-place-editable-table-demo.herokuapp.com');
      ga('send', 'pageview');

  %body
    .header
      .flash_message
        = render 'flash_message'
    .container
      = yield